#!/bin/bash

clear

# Version control and package management

echo "Installing version control and package management tools..."

## Homebrew
echo -n "  - Homebrew: "
if command -v brew &>/dev/null; then
	echo "DONE"
else
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	echo "DONE"
fi

## Git
echo -n "  - Git: "
if command -v git &>/dev/null; then
	echo "DONE"
else
	# on Macos, git is installed with Xcode Command Line Tools
	git --version
	echo "DONE"
fi

## GitHub CLI
echo -n "  - GitHub CLI: "
if command -v gh &>/dev/null; then
	echo "DONE"
else
	brew install gh
	echo "DONE"
fi

# check if gh is authenticated, otherwise log in
echo
echo -n "Checking GitHub CLI authentication... "
if gh auth status | grep -q "Logged in to github.com"; then
	echo "authenticated"
else
	echo "unauthenticated"
	echo "Please authenticate GitHub CLI"
	gh auth login
fi

# Terminal and shell

echo "Installing terminal and shell..."

## zsh
echo -n "  - Zsh: "
if command -v zsh &>/dev/null; then
	echo "DONE"
else
	brew install zsh
	echo "DONE"
fi

## oh-my-zsh
echo -n "  - oh-my-zsh: "
if [ -d "$HOME/.oh-my-zsh" ]; then
	echo "DONE"
else
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	echo "DONE"
fi

## powerlevel10k
echo -n "  - powerlevel10k: "
if [ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]; then
	echo "DONE"
else
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
	echo "DONE"
fi

## WezTerm
echo -n "  - WezTerm: "
if command -v wezterm &>/dev/null; then
	echo "DONE"
else
	brew install --cask wezterm
	brew install wezterm
	echo "DONE"
fi

# CLI tools
#
echo "Installing CLI tools..."

## bat
echo -n "  - bat: "
if command -v bat &>/dev/null; then
	echo "DONE"
else
	brew install bat
	echo "DONE"
fi

## direnv
echo -n "  - direnv: "
if command -v direnv &>/dev/null; then
	echo "DONE"
else
	brew install direnv
	echo "DONE"
fi

## fzf
echo -n "  - fzf: "
if command -v fzf &>/dev/null; then
	echo "DONE"
else
	brew install fzf
	echo "DONE"
fi

## GitHub CLI Copilot
echo -n "  - GitHub CLI Copilot: "
if gh extension list | grep copilot &>/dev/null; then
	echo "DONE"
else
	gh extension install github/gh-copilot
	echo "DONE"
fi

## lazygit
echo -n "  - lazygit: "
if command -v lazygit &>/dev/null; then
	echo "DONE"
else
	brew install lazygit
	echo "DONE"
fi

## k9s
echo -n "  - k9s: "
if command -v k9s &>/dev/null; then
	echo "DONE"
else
	brew install k9s
	echo "DONE"
fi

## lsd
echo -n "  - lsd: "
if command -v lsd &>/dev/null; then
	echo "DONE"
else
	brew install lsd
	echo "DONE"
fi

## NeoVim
echo -n "  - NeoVim: "
if command -v nvim &>/dev/null; then
	echo "DONE"
else
	brew install neovim
	echo "DONE"
fi

## ripgrep
echo -n "  - ripgrep: "
if command -v rg &>/dev/null; then
	echo "DONE"
else
	brew install ripgrep
	echo "DONE"
fi

## Stow
echo -n "  - Stow: "
if command -v stow &>/dev/null; then
	echo "DONE"
else
	brew install stow
	echo "DONE"
fi

## wget
echo -n "  - wget: "
if command -v wget &>/dev/null; then
	echo "DONE"
else
	brew install wget
	echo "DONE"
fi

## Zoxide
echo -n "  - Zoxide: "
if command -v zoxide &>/dev/null; then
	echo "DONE"
else
	brew install zoxide
	echo "DONE"
fi

# Configure

echo "Configuring dotfiles..."
cd "$(git rev-parse --show-toplevel)"
stow .

echo "Configuring local zsh config"
echo >>~/.zshrc.local
echo "git config --global gpg.ssh.program /Applications/1Password.app/Contents/MacOS/op-ssh-sign" >>~/.zshrc.local

echo "Done!"
