#!/bin/bash

check_installed() {
  if command -v $1 &>/dev/null; then
    return 1
  else
    return 0
  fi
}

brew_install() {
  if check_installed $1; then
    brew install $1
  fi
  echo "$1... Done"
}

clear

# Core
sudo apt install -y build-essential

# Version control and package management
## git
brew_install git
brew_install gh
# TODO: configure GitHub CLI Copilot

# brew
if check_installed brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  (
    echo
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
  ) >>/home/phil/.zshrc.local
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
echo "Brew... Done"

# Terminal and shell
## zsh
brew_install zsh

## oh my zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "Installing omz"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
fi
echo "oh-my-zsh... Done"

## powerlevel10k
if [ ! -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi
echo "powerlevel10k... Done"

# CLI Tools
## bat
brew_install bat

## direnv
brew_install direnv

## fzf
if check_installed fzf; then
  brew_install fzf
  FZF_BASE=$(which fzf)
  (
    echo
    echo "export FZF_BASE=${FZF_BASE}"
  ) >>/home/phil/.zshrc.local
fi

## lazygit
brew_install lazygit

## k9s
brew_install k9s

## lsd
brew_install lsd

## neovim
if check_installed nvim; then
  brew_install neovim
else
  echo "neovim... Done"
fi

## stow
brew_install stow

## wget
brew_install wget

## zoxide
brew_install zoxide

# Cleanup
sudo apt autoremove

## Link config files
echo "Configuring dotfiles..."
cd "$(git rev-parse --show-toplevel)"
stow .

echo "Configuring local zsh config"
echo >>~/.zshrc.local
echo "git config --global gpg.ssh.program /mnt/c/Users/phili/AppData/Local/1Password/app/8/op-ssh-sign.exe" >>~/.zshrc.local

echo "Done!"
